services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    ports:
      - "8080:80"
    networks:
      - security-scan
    restart: unless-stopped

networks:
  security-scan:
    name: security-scan
